### ISSUE TITLE
Cors problem on Web

### ISSUE THREAD

**Issue by dannycortesv** [WorkWithAfridi/IP_Country_Lookup-Package#1]
The plugin stop working for web and also app, seems that the provider added another layer of security

**Comment by Idoadler1** [comment]
i am also having CORS problem

**Comment by urmamb** [comment]
I also have this CORS issue on web.

**Comment by WorkWithAfridi** [comment]
@dannycortesv, @urmamb guys, it seems to be working on App and on Web, just tested it on Android, iOS, as well as Web. 🤔 
Maybe try caching the info so that you don't have to call it every time the app boots and rate limit yourself? 

![CleanShot 2024-07-06 at 18 49 47@2x](https://github.com/WorkWithAfridi/IP_Country_Lookup-Package/assets/62285418/799d9466-531c-4830-809e-1a37497cd6a2)
![CleanShot 2024-07-06 at 18 48 33@2x](https://github.com/WorkWithAfridi/IP_Country_Lookup-Package/assets/62285418/e093387d-03b2-4012-84f7-7c5323802624)
